CREATE TABLE issue
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author_id   BIGINT                                  NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    category    INTEGER                                 NOT NULL,
    is_resolved BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_issue PRIMARY KEY (id)
);