/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gametrader.api;

import com.gametrader.api.model.IssueDto;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IssueControllerApi
 */
@Ignore
public class IssueControllerApiTest {

    private final IssueControllerApi api = new IssueControllerApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createIssueTest() {
        IssueDto issueDto = null;
        api.createIssue(issueDto);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllPostsTest() {
        List<IssueDto> response = api.getAllPosts();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllPostsByAuthorIdTest() {
        Long authorId = null;
        List<IssueDto> response = api.getAllPostsByAuthorId(authorId);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllPostsByAuthorId1Test() {
        List<IssueDto> response = api.getAllPostsByAuthorId1();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getAllPostsByCategoryTest() {
        String category = null;
        List<IssueDto> response = api.getAllPostsByCategory(category);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPostByIdTest() {
        Long id = null;
        IssueDto response = api.getPostById(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateIssueTest() {
        IssueDto issueDto = null;
        api.updateIssue(issueDto);

        // TODO: test validations
    }
    
}
